'use strict'
const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { PackageStore, createManifest, verifyPackage, MANIFEST, ORIGIN, REQUIRED_ROUTES } = require('./package-store')
const { resolveRequest, createHandler } = require('./protocol')

function setup(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'fullsite-ui-store-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  return { root, store: new PackageStore(path.join(root, 'installed')) }
}
function fixture(root, release) {
  const directory = path.join(root, release)
  fs.mkdirSync(directory)
  function write(file, body) { fs.mkdirSync(path.dirname(path.join(directory, file)), { recursive: true }); fs.writeFileSync(path.join(directory, file), body) }
  for (const route of REQUIRED_ROUTES) {
    write(`${route.slice(1)}.html`, `<html><body>${release}: ${route}</body></html>`)
    write(`${route.slice(1)}.txt`, `0:${JSON.stringify({ release, route })}`)
  }
  write('_next/static/chunks/screen.js', `window.release = '${release}'`)
  write('_next/static/css/style.css', 'body { color: black; }')
  return createManifest(directory)
}
test('complete release is durable across restarts and the previous release is retained', t => {
  const { root, store } = setup(t)
  const first = fixture(root, 'first'), second = fixture(root, 'second')
  store.install(first.directory)
  store.install(second.directory)
  assert.equal(new PackageStore(store.directory).load().manifest.revision, second.manifest.revision)
  assert.equal(store.state().previous, first.manifest.revision)
  assert.equal(verifyPackage(path.join(store.versions, first.manifest.revision)).manifest.revision, first.manifest.revision)
  assert.equal(store.install(second.directory).manifest.revision, second.manifest.revision)
  assert.equal(store.state().previous, first.manifest.revision, 'idempotent boot preserves recovery release')
})
test('truncated, corrupt, incomplete and extra files never replace the active release', t => {
  const { root, store } = setup(t)
  const first = fixture(root, 'first'), bad = fixture(root, 'bad')
  store.install(first.directory)
  const original = fs.readFileSync(path.join(bad.directory, 'pos.html'))
  fs.writeFileSync(path.join(bad.directory, 'pos.html'), 'truncated')
  assert.throws(() => store.install(bad.directory), /integrity/)
  fs.writeFileSync(path.join(bad.directory, 'pos.html'), original)
  fs.writeFileSync(path.join(bad.directory, 'unlisted.js'), 'malicious')
  assert.throws(() => store.install(bad.directory), /Unlisted/)
  fs.rmSync(path.join(bad.directory, 'unlisted.js'))
  fs.rmSync(path.join(bad.directory, 'pos/corte.txt'))
  assert.throws(() => createManifest(bad.directory), /Incomplete/)
  assert.equal(store.load().manifest.revision, first.manifest.revision)
})
test('failed activation leaves old pointer usable and a later restart can install verified bytes', t => {
  const { root, store } = setup(t)
  const first = fixture(root, 'first'), second = fixture(root, 'second')
  store.install(first.directory)
  store.writeState = () => { throw new Error('ENOSPC during activation') }
  assert.throws(() => store.install(second.directory), /ENOSPC/)
  const recovered = new PackageStore(store.directory)
  assert.equal(recovered.load().manifest.revision, first.manifest.revision)
  assert.equal(recovered.install(second.directory).manifest.revision, second.manifest.revision)
  assert.equal(recovered.state().previous, first.manifest.revision)
})
test('damaged active release recovers previous version without reinstalling the rejected revision', t => {
  const { root, store } = setup(t)
  const first = fixture(root, 'first'), second = fixture(root, 'second')
  store.install(first.directory); store.install(second.directory)
  fs.writeFileSync(path.join(store.versions, second.manifest.revision, 'pos.html'), 'corrupted')
  const recovered = new PackageStore(store.directory).load()
  assert.equal(recovered.recovered, true)
  assert.equal(recovered.manifest.revision, first.manifest.revision)
  assert.throws(() => store.install(second.directory), /previously rejected/)
  assert.equal(store.load().manifest.revision, first.manifest.revision)
})
test('symlinks and traversal in packages or activation pointers are rejected', t => {
  const { root, store } = setup(t)
  const bundle = fixture(root, 'bundle')
  fs.symlinkSync(path.join(bundle.directory, 'pos.html'), path.join(bundle.directory, 'escape'))
  assert.throws(() => verifyPackage(bundle.directory), /Unsafe/)
  fs.rmSync(path.join(bundle.directory, 'escape'))
  const manifest = JSON.parse(fs.readFileSync(path.join(bundle.directory, MANIFEST)))
  manifest.files['../escape'] = { bytes: 0, sha256: '0'.repeat(64) }
  fs.writeFileSync(path.join(bundle.directory, MANIFEST), JSON.stringify(manifest))
  assert.throws(() => store.install(bundle.directory), /paths/)
  fs.writeFileSync(store.pointer, JSON.stringify({ active: '../../escape' }))
  assert.throws(() => store.load(), /activation pointer/)
})
test('queries, Next RSC, trailing slashes and encoded traversal resolve without mixing releases', t => {
  const { root } = setup(t)
  const { manifest } = fixture(root, 'bundle')
  const request = (url, init) => resolveRequest(new Request(ORIGIN + url, init), manifest)
  assert.deepEqual(request('/pos?mesa=1&nombre=Dos'), { file: 'pos.html' })
  assert.deepEqual(request('/pos/mesas/?x=1'), { file: 'pos/mesas.html' })
  assert.deepEqual(request('/pos/mesas?_rsc=abc'), { file: 'pos/mesas.txt' })
  assert.deepEqual(request('/pos/mesas', { headers: { RSC: '1' } }), { file: 'pos/mesas.txt' })
  assert.deepEqual(request('/pos/mesas.txt?cache=123'), { file: 'pos/mesas.txt' })
  for (const invalid of ['/pos/%2e%2e%2fsecret', '/%2e%2e%5csecret', '/%00file']) assert.equal(request(invalid).status, 400)
  assert.equal(request('/_next/static/chunks/new-cloud-release.js').status, 404)
  assert.equal(request('/api/pos/pin', { method: 'POST', body: '{}' }).network, true)
  assert.equal(request('/pos', { method: 'POST' }).status, 405)
})
test('handler serves verified bytes and forwards API credentials/body without serving cached data', async t => {
  const { root } = setup(t)
  const bundle = fixture(root, 'bundle')
  let forwarded
  const handler = createHandler(bundle, async request => { forwarded = request; return Response.json({ online: true }) })
  const page = await handler(new Request(ORIGIN + '/pos?mesa=2'))
  assert.equal(page.status, 200)
  assert.equal(page.headers.get('x-fullsite-ui-revision'), bundle.manifest.revision)
  assert.equal(page.headers.get('cache-control'), 'no-store')
  assert.match(await page.text(), /bundle: \/pos/)
  const api = new Request(ORIGIN + '/api/pos/pin', { method: 'POST', headers: { Authorization: 'Bearer synthetic' }, body: '{"pin":"1234"}' })
  assert.equal((await handler(api)).status, 200)
  assert.equal(forwarded, api)
  assert.equal(forwarded.headers.get('authorization'), 'Bearer synthetic')
  assert.equal(await forwarded.text(), '{"pin":"1234"}')
  assert.equal((await handler(new Request(ORIGIN + '/_next/new.js'))).status, 404)
  fs.writeFileSync(path.join(bundle.directory, 'pos.html'), 'modified after boot')
  assert.equal((await handler(new Request(ORIGIN + '/pos'))).status, 503)
})
test('the protocol response itself authorizes the installed bridge port and packaging rejects absent UI', async t => {
  const { root } = setup(t)
  const bundle = fixture(root, 'ui-bundle')
  const handler = createHandler(bundle, () => { throw new Error('Unexpected WAN') }, 19027)
  const csp = (await handler(new Request(ORIGIN + '/pos'))).headers.get('content-security-policy')
  assert(csp.includes('http://127.0.0.1:19027'))
  assert(csp.includes('ws://127.0.0.1:19027'))
  const beforePack = require('../scripts/verify-offline-ui.cjs')
  await beforePack({ appDir: root })
  await beforePack({ packager: { info: { appDir: root } } })
  await assert.rejects(beforePack({ appDir: path.join(root, 'missing') }))
})
